const products = [
  {
    id: 1,
    slug: "dibi-face-perfection-triphasic-micellar-water",
    title: "DIBI Face Perfection Triphasic Micellar Water 200ML",
    description:
      "Her får man en 3-faset løsning: Fjerner makeup, og øyenmakeup Renser huden for skitt og urenheter Har Skin Tonic effekt Rist flasken før bruk, for å blande de tre faser!",
    category: "Hudpleie",
    brand: "DIBI Milano",
    createdAt: "2021-06-16T12:00:00Z",
    updatedAt: "2021-06-16T12:00:00Z",
    mainImage: "/assets/products/dibi_face_perf.png",
    price: "230",
    specialPrice: "199",
    costPrice: "499",
    stock: 0,
  },
  {
    id: 2,
    slug: "dibi-filler-code",
    title: "DIBI Filler Code Serum 7X2ML",
    description:
      "Synlig glattere hud. Flytende serum i singel-doser som jevner ut huden. Rik på Peptide 5, en aktiv ingrediens som bekjemper synligheten av linjer og virker oppstrammende på huden.",
    category: "Hudpleie",
    brand: "DIBI Milano",
    createdAt: "2021-06-16T12:00:00Z",
    updatedAt: "2021-06-16T12:00:00Z",
    mainImage: "/assets/products/dibi-filler-code.png",
    price: "400",
    specialPrice: "",
    costPrice: "899",
    stock: 4,
  },
  {
    id: 3,
    slug: "dibi-nutri-age-regenerating-pro-resilience-cream",
    title:
      "DIBI Nutri-age Regenerating Pro-resilience Cream with UV filters 50ML",
    description:
      "Huden føles ikke stram og for liten når du bruker denne kremen. Nærende prebiotisk krem med UV- filter, regenererende og antioksidant",
    category: "Hudpleie",
    brand: "DIBI Milano",
    createdAt: "2021-06-16T12:00:00Z",
    updatedAt: "2021-06-16T12:00:00Z",
    mainImage:
      "/assets/products/Skjermbilde-2023-12-06-kl-152859_1115637d091d73bea5ad0f6d1c323c49_1.png",
    price: "800",
    specialPrice: "",
    costPrice: "1790",
    stock: 8,
  },
];
export { products };

const productslist = [
  {
    id: 1,
    slug: "dibi-face-perfection-triphasic-micellar-water",
    title: "DIBI Face Perfection Triphasic Micellar Water 200ML",
    description:
      "Her får man en 3-faset løsning: Fjerner makeup, og øyenmakeup Renser huden for skitt og urenheter Har Skin Tonic effekt Rist flasken før bruk, for å blande de tre faser!",
    category: "Hudpleie",
    brand: "DIBI Milano",
    createdAt: "2021-06-16T12:00:00Z",
    updatedAt: "2021-06-16T12:00:00Z",
    mainImage: "/assets/products/dibi_face_perf.png",
    price: "230",
    specialPrice: "199",
    costPrice: "499",
    stock: 0,
  },
  {
    id: 2,
    slug: "dibi-filler-code",
    title: "DIBI Filler Code Serum 7X2ML",
    description:
      "Synlig glattere hud. Flytende serum i singel-doser som jevner ut huden. Rik på Peptide 5, en aktiv ingrediens som bekjemper synligheten av linjer og virker oppstrammende på huden.",
    category: "Hudpleie",
    brand: "DIBI Milano",
    createdAt: "2021-06-16T12:00:00Z",
    updatedAt: "2021-06-16T12:00:00Z",
    mainImage: "/assets/products/dibi-filler-code.png",
    price: "400",
    specialPrice: "",
    costPrice: "899",
    stock: 4,
  },
  {
    id: 3,
    slug: "dibi-nutri-age-regenerating-pro-resilience-cream",
    title:
      "DIBI Nutri-age Regenerating Pro-resilience Cream with UV filters 50ML",
    description:
      "Huden føles ikke stram og for liten når du bruker denne kremen. Nærende prebiotisk krem med UV- filter, regenererende og antioksidant",
    category: "Hudpleie",
    brand: "DIBI Milano",
    createdAt: "2021-06-16T12:00:00Z",
    updatedAt: "2021-06-16T12:00:00Z",
    mainImage:
      "/assets/products/Skjermbilde-2023-12-06-kl-152859_1115637d091d73bea5ad0f6d1c323c49_1.png",
    price: "800",
    specialPrice: "",
    costPrice: "1790",
    stock: 8,
  },
];
export { productslist };

const orders = [
  {
    id: 1,
    orderNumber: "S263273233",
    total: "4259",
    createdAt: "2021-06-16T12:00:00Z",
    createdBy: "Ola Nordmann",
    status: "Levert",
    products: [
      {
        id: 1,
        slug: "dibi-face-perfection-triphasic-micellar-water",
        title: "DIBI Face Perfection Triphasic Micellar Water 200ML",
        description:
          "Her får man en 3-faset løsning: Fjerner makeup, og øyenmakeup Renser huden for skitt og urenheter Har Skin Tonic effekt Rist flasken før bruk, for å blande de tre faser!",
        price: "230",
        brand: "DIBI Milano",
        mainImage: "/assets/products/dibi_face_perf.png",
        quantity: 2,
      },
      {
        id: 2,
        slug: "dibi-filler-code",
        title: "DIBI Filler Code Serum 7X2ML",
        description:
          "Synlig glattere hud. Flytende serum i singel-doser som jevner ut huden. Rik på Peptide 5, en aktiv ingrediens som bekjemper synligheten av linjer og virker oppstrammende på huden.",
        price: "400",
        brand: "DIBI Milano",
        mainImage: "/assets/products/dibi-filler-code.png",
        quantity: 1,
      },
      {
        id: 3,
        slug: "dibi-nutri-age-regenerating-pro-resilience-cream",
        title:
          "DIBI Nutri-age Regenerating Pro-resilience Cream with UV filters 50ML",
        description:
          "Huden føles ikke stram og for liten når du bruker denne kremen. Nærende prebiotisk krem med UV- filter, regenererende og antioksidant",
        price: "800",
        brand: "DIBI Milano",
        mainImage:
          "/assets/products/Skjermbilde-2023-12-06-kl-152859_1115637d091d73bea5ad0f6d1c323c49_1.png",
        quantity: 1,
      },
    ],
  },
  {
    id: 2,
    orderNumber: "S263273235",
    total: "5809",
    createdAt: "2021-06-17T12:00:00Z",
    createdBy: "Ola Nordmann",
    status: "Levert",
    products: [
      {
        id: 1,
        slug: "dibi-face-perfection-triphasic-micellar-water",
        title: "DIBI Face Perfection Triphasic Micellar Water 200ML",
        description:
          "Her får man en 3-faset løsning: Fjerner makeup, og øyenmakeup Renser huden for skitt og urenheter Har Skin Tonic effekt Rist flasken før bruk, for å blande de tre faser!",
        price: "230",
        brand: "DIBI Milano",
        mainImage: "/assets/products/dibi_face_perf.png",
        quantity: 12,
      },
      {
        id: 2,
        slug: "dibi-filler-code",
        title: "DIBI Filler Code Serum 7X2ML",
        description:
          "Synlig glattere hud. Flytende serum i singel-doser som jevner ut huden. Rik på Peptide 5, en aktiv ingrediens som bekjemper synligheten av linjer og virker oppstrammende på huden.",
        price: "400",
        brand: "DIBI Milano",
        mainImage: "/assets/products/dibi-filler-code.png",
        quantity: 11,
      },
    ],
  },
];
export { orders };

const categories = [
  {
    id: 1,
    name: "Annet",
    categories: [
      "Display",
      "Hårfjerning",
      "Selvbruning",
      "Tilbehør",
      "Øyenbryn",
      "Vipper og bryn",
      "Voks og utstyr",
    ],
  },
  {
    id: 2,
    name: "Barn",
  },
  {
    id: 2,
    name: "Diverse",
  },
  {
    id: 3,
    name: "Hår",
    categories: [
      "Gavesett",
      "Krem",
      "Kropp",
      "Kur",
      "Maske",
      "pleie",
      "Rens",
      "Shampoo",
      "styling",
      "Øyekrem",
    ],
  },
  {
    id: 4,
    name: "Hårpleie",
    categories: ["Balsam", "Tilbehør", "Børste og kam", "Stylingverktøy"],
  },
  {
    id: 5,
    name: "Hudpleie",
    categories: [
      "Ansikt",
      "Ansiktsmaske",
      "Balsam",
      "Concealer",
      "Display",
      "Eyeliner",
      "Foundation",
      "Hender",
      "Highlighter",
      "Kit",
      "Koster",
      "Kropp",
      "Kur",
      "Leppepomade",
      "Lepper",
      "Lipgloss",
      "Lipstick",
      "Mascara",
      "Neglelakk",
      "Negler",
      "Peeling",
      "Primer",
      "Pudder",
      "Rens",
      "Rouge og bronzer",
      "Serum",
      "Shampoo",
      "Tilbehør",
      "Toner",
      "Øyenskygge",
      "Øyeskygge",
      "Øyne",
      "Øyne - Serum",
      "Øyne - Øyekrem",

      "Øynebryn",
      "Krem",
    ],
  },
  {
    id: 5,
    name: "Sminke",
    categories: [
      "Ansikt",
      "Concealer",
      "Foundation",
      "Highlight og Contouring",
      "Primer",
      "Pudder",
      "Rens",
      "Rouge og Bronzer",
      "Display",
      "Display - Krem",
      "Display - Lipgloss",
      "Display - Øyenbryn",
      "Koster",
      "Lepper",
      "Lepper - Leppepomade",
      "Lepper - Leppestift",
      "Lepper - Lipgloss",
      "Lepper - Lipliner",
      "Negler",
      "Negler - Neglelakk",
      "Negler - Neglelakkfjerner",
      "Sminkesett",
      "Sminkesett - Lipgloss",

      "Smittevern",
      "Test",
    ],
  },
];
export { categories };

const rawCategories = [
  "Annet >",
  "Annet > Display",
  "Annet > hårfjerning",
  "Annet > Selvbruning",
  "Annet > Tilbehør",
  "Annet > Tilbehør > Øyenbryn",
  "Annet > Vipper og bryn",
  "Annet > Voks og utstyr",
  "Barn",
  "DIVERSE",
  "Hår > Gavesett",
  "Hår > Krem",
  "Hår > Kropp",
  "Hår > Kur",
  "Hår > Maske",
  "Hår > pleie",
  "Hår > Rens",
  "Hår > Shampoo",
  "Hår > styling",
  "Hår > Øyekrem",
  "Hårpleie >",
  "Hårpleie > Balsam",
  "Hårpleie > Tilbehør > Børste og kam",
  "Hårpleie > Tilbehør hår > Stylingverktøy",
  "Hudpleie > Ansikt",
  "Hudpleie > Ansiktsmaske",
  "Hudpleie > Balsam",
  "Hudpleie > Concealer",
  "Hudpleie > Display",
  "Hudpleie > Eyeliner",
  "Hudpleie > Foundation",
  "Hudpleie > Hender",
  "Hudpleie > Highlighter",
  "Hudpleie > Kit",
  "Hudpleie > Koster",
  "Hudpleie > Kropp",
  "Hudpleie > Kur",
  "Hudpleie > Leppepomade",
  "Hudpleie > Lepper",
  "Hudpleie > Lipgloss",
  "Hudpleie > Lipstick",
  "Hudpleie > Mascara",
  "Hudpleie > Neglelakk",
  "Hudpleie > Negler",
  "Hudpleie > Peeling",
  "Hudpleie > Primer",
  "Hudpleie > Pudder",
  "Hudpleie > Rens",
  "Hudpleie > Rouge og bronzer",
  "Hudpleie > Serum",
  "Hudpleie > Shampoo",
  "Hudpleie > Tilbehør",
  "Hudpleie > Toner",
  "Hudpleie > Øyenskygge",
  "Hudpleie > Øyeskygge",
  "Hudpleie > Øyne",
  "Hudpleie > Øyne > Serum",
  "Hudpleie > Øyne > Øyekrem",
  "Hudpleie > Øynebryn",
  "Hudpleie >Krem",
  "La Pizza",
  "Sminke",
  "Sminke > Ansikt",
  "Sminke > Ansikt > Concealer",
  "Sminke > Ansikt > Foundation",
  "Sminke > Ansikt > Highlight og Contouring",
  "Sminke > Ansikt > Primer",
  "Sminke > Ansikt > Pudder",
  "Sminke > Ansikt > Rens",
  "Sminke > Ansikt > Rouge og Bronzer",
  "Sminke > Display",
  "Sminke > Display > Krem",
  "Sminke > Display > Lipgloss",
  "Sminke > Display > Øyenbryn",
  "Sminke > Koster",
  "Sminke > Lepper > Leppepomade",
  "Sminke > Lepper > Leppestift",
  "Sminke > Lepper > Lipgloss",
  "Sminke > Lepper > Lipliner",
  "Sminke > Negler",
  "Sminke > Negler > Neglelakk",
  "Sminke > Negler > Neglelakkfjerner",
  "Sminke > Sminkesett",
  "Sminke > Sminkesett > Lipgloss",
  "Sminke > Tilbehør",
  "Sminke > Tilbehør > Krem",
  "Sminke > Øyne",
  "Sminke > Øyne > Eyeliner",
  "Sminke > Øyne > Mascara",
  "Sminke > Øyne > Primer",
  "Sminke > Øyne > Serum",
  "Sminke > Øyne > Øyenbryn",
  "Sminke > Øyne > Øyenskygge",
  "Smittevern",
  "Test",
];
export { rawCategories };
{
  /*
        {
        name: "Display",
        subcategories: ["Display", "Krem", "Lipgloss", "Øyenbryn"],
      },
      "Koster",
      { Lepper: ["Leppepomade", "Leppestift", "Lipgloss", "Lipliner"] },
      { Negler: ["Neglelakk", "Neglelakkfjerner"] },
      { Sminkesett: ["Sminkesett", "Lipgloss"] },
      { Tilbehør: ["Tilbehør", "Krem"] },
      {
        Øyne: [
          "Eyeliner",
          "Mascara",
          "Primer",
          "Serum",
          "Øyenbryn",
          "Øyenskygge",
        ],
      },
  */
}

const brands = [
  { name: "Acorelle" },
  { name: "Ardell" },
  { name: "Beauté Pacifique" },
  { name: "Beautyblender" },
  { name: "Bronx" },
  { name: "By Victoria" },
  { name: "Color Wow" },
  { name: "DIBI Milano" },
  { name: "Eco By Sonya" },
  { name: "Ecooking" },
  { name: "EmerginC" },
  { name: "Evagarden" },
  { name: "Exuviance" },
  { name: "Exuviance Professional" },
  { name: "Fab Brows" },
  { name: "Fan Palm" },
  { name: "Fred Hamelten" },
  { name: "GB" },
  { name: "GIGI" },
  { name: "Glominerals" },
  { name: "Heliocare" },
  { name: "Hot Makeup" },
  { name: "ICON" },
  { name: "Idema" },
  { name: "Intensive" },
  { name: "Kent" },
  { name: "Kocostar" },
  { name: "Lash Bomb" },
  { name: "Lille Kanin" },
  { name: "Living Proof" },
  { name: "Lovcos" },
  { name: "Lulu`s" },
  { name: "Makeup Revolution London" },
  { name: "MAST" },
  { name: "Maya Water" },
  { name: "Mine Tan" },
  { name: "miriam quevedo" },
  { name: "Nilens Jord" },
  { name: "O&M" },
  { name: "Ofra" },
  { name: "Ofra" },
  { name: "Oway" },
  { name: "Premax" },
  { name: "Proclé" },
  { name: "Real Techniques" },
  { name: "Sanzi Beauty" },
  { name: "Sara Happ" },
  { name: "Skin Vital" },
  { name: "Solarium" },
  { name: "Solutions Cosmeceuticals" },
  { name: "Sunspa" },
  { name: "thebalm" },
  { name: "Vita Liberata" },
  { name: "Workstyle" },
  { name: "WunderBrow" },
  { name: "ZAO" },
];
export { brands };

const rawcategorieslist = [
  { id: 1, name: "Annet" },
  { id: 2, name: "Annet > Display" },
  { id: 3, name: "Annet > hårfjerning" },
  { id: 4, name: "Annet > Selvbruning" },
  { id: 5, name: "Annet > Tilbehør" },
  { id: 6, name: "Annet > Tilbehør > Øyenbryn" },
  { id: 7, name: "Annet > Vipper og bryn" },
  { id: 8, name: "Annet > Voks og utstyr" },
  { id: 9, name: "Barn" },
  { id: 10, name: "DIVERSE" },
  { id: 11, name: "Hår > Gavesett" },
  { id: 12, name: "Hår > Krem" },
  { id: 13, name: "Hår > Kropp" },
  { id: 14, name: "Hår > Kur" },
  { id: 15, name: "Hår > Maske" },
  { id: 16, name: "Hår > pleie" },
  { id: 17, name: "Hår > Rens" },
  { id: 18, name: "Hår > Shampoo" },
  { id: 19, name: "Hår > styling" },
  { id: 20, name: "Hår > Øyekrem" },
  { id: 21, name: "Hårpleie >" },
  { id: 22, name: "Hårpleie > Balsam" },
  { id: 23, name: "Hårpleie > Tilbehør > Børste og kam" },
  { id: 24, name: "Hårpleie > Tilbehør hår > Stylingverktøy" },
  { id: 25, name: "Hudpleie > Ansikt" },
  { id: 26, name: "Hudpleie > Ansiktsmaske" },
  { id: 27, name: "Hudpleie > Balsam" },
  { id: 28, name: "Hudpleie > Concealer" },
  { id: 29, name: "Hudpleie > Display" },
  { id: 30, name: "Hudpleie > Eyeliner" },
  { id: 31, name: "Hudpleie > Foundation" },
  { id: 32, name: "Hudpleie > Hender" },
  { id: 33, name: "Hudpleie > Highlighter" },
  { id: 34, name: "Hudpleie > Kit" },
  { id: 35, name: "Hudpleie > Koster" },
  { id: 36, name: "Hudpleie > Kropp" },
  { id: 37, name: "Hudpleie > Kur" },
  { id: 38, name: "Hudpleie > Leppepomade" },
  { id: 39, name: "Hudpleie > Lepper" },
  { id: 40, name: "Hudpleie > Lipgloss" },
  { id: 41, name: "Hudpleie > Lipstick" },
  { id: 42, name: "Hudpleie > Mascara" },
  { id: 43, name: "Hudpleie > Neglelakk" },
  { id: 44, name: "Hudpleie > Negler" },
  { id: 45, name: "Hudpleie > Peeling" },
  { id: 46, name: "Hudpleie > Primer" },
  { id: 47, name: "Hudpleie > Pudder" },
  { id: 48, name: "Hudpleie > Rens" },
  { id: 49, name: "Hudpleie > Rouge og bronzer" },
  { id: 50, name: "Hudpleie > Serum" },
  { id: 51, name: "Hudpleie > Shampoo" },
  { id: 52, name: "Hudpleie > Tilbehør" },
  { id: 53, name: "Hudpleie > Toner" },
  { id: 54, name: "Hudpleie > Øyenskygge" },
  { id: 55, name: "Hudpleie > Øyeskygge" },
  { id: 56, name: "Hudpleie > Øyne" },
  { id: 57, name: "Hudpleie > Øyne > Serum" },
  { id: 58, name: "Hudpleie > Øyne > Øyekrem" },
  { id: 59, name: "Hudpleie > Øynebryn" },
  { id: 60, name: "Hudpleie >Krem" },
  { id: 61, name: "La Pizza" },
  { id: 62, name: "Sminke" },
  { id: 63, name: "Sminke > Ansikt" },
  { id: 64, name: "Sminke > Ansikt > Concealer" },
  { id: 65, name: "Sminke > Ansikt > Foundation" },
  { id: 66, name: "Sminke > Ansikt > Highlight og Contouring" },
  { id: 67, name: "Sminke > Ansikt > Primer" },
  { id: 68, name: "Sminke > Ansikt > Pudder" },
  { id: 69, name: "Sminke > Ansikt > Rens" },
  { id: 70, name: "Sminke > Ansikt > Rouge og Bronzer" },
  { id: 71, name: "Sminke > Display" },
  { id: 72, name: "Sminke > Display > Krem" },
  { id: 73, name: "Sminke > Display > Lipgloss" },
  { id: 74, name: "Sminke > Display > Øyenbryn" },
  { id: 75, name: "Sminke > Koster" },
  { id: 76, name: "Sminke > Lepper > Leppepomade" },
  { id: 77, name: "Sminke > Lepper > Leppestift" },
  { id: 78, name: "Sminke > Lepper > Lipgloss" },
  { id: 79, name: "Sminke > Lepper > Lipliner" },
  { id: 80, name: "Sminke > Negler" },
  { id: 81, name: "Sminke > Negler > Neglelakk" },
  { id: 82, name: "Sminke > Negler > Neglelakkfjerner" },
  { id: 83, name: "Sminke > Sminkesett" },
  { id: 84, name: "Sminke > Sminkesett > Lipgloss" },
  { id: 85, name: "Sminke > Tilbehør" },
  { id: 86, name: "Sminke > Tilbehør > Krem" },
  { id: 87, name: "Sminke > Øyne" },
  { id: 88, name: "Sminke > Øyne > Eyeliner" },
  { id: 89, name: "Sminke > Øyne > Mascara" },
  { id: 90, name: "Sminke > Øyne > Primer" },
  { id: 91, name: "Sminke > Øyne > Serum" },
  { id: 92, name: "Sminke > Øyne > Øyenbryn" },
  { id: 93, name: "Sminke > Øyne > Øyenskygge" },
  { id: 94, name: "Smittevern" },
  { id: 95, name: "Test" },
];
export { rawcategorieslist };

const categoriestree = [
  "Annet",
  "Annet > Display",
  "Annet > hårfjerning",
  "Annet > Selvbruning",
  "Annet > Tilbehør",
  "Annet > Tilbehør > Øyenbryn",
  "Annet > Vipper og bryn",
  "Annet > Voks og utstyr",
  "Barn",
  "DIVERSE",
  "Hår > Gavesett",
  "Hår > Krem",
  "Hår > Kropp",
  "Hår > Kur",
  "Hår > Maske",
  "Hår > pleie",
  "Hår > Rens",
  "Hår > Shampoo",
  "Hår > styling",
  "Hår > Øyekrem",
  "Hårpleie >",
  "Hårpleie > Balsam",
  "Hårpleie > Tilbehør > Børste og kam",
  "Hårpleie > Tilbehør hår > Stylingverktøy",
  "Hudpleie > Ansikt",
  "Hudpleie > Ansiktsmaske",
  "Hudpleie > Balsam",
  "Hudpleie > Concealer",
  "Hudpleie > Display",
  "Hudpleie > Eyeliner",
  "Hudpleie > Foundation",
  "Hudpleie > Hender",
  "Hudpleie > Highlighter",
  "Hudpleie > Kit",
  "Hudpleie > Koster",
  "Hudpleie > Kropp",
  "Hudpleie > Kur",
  "Hudpleie > Leppepomade",
  "Hudpleie > Lepper",
  "Hudpleie > Lipgloss",
  "Hudpleie > Lipstick",
  "Hudpleie > Mascara",
  "Hudpleie > Neglelakk",
  "Hudpleie > Negler",
  "Hudpleie > Peeling",
  "Hudpleie > Primer",
  "Hudpleie > Pudder",
  "Hudpleie > Rens",
  "Hudpleie > Rouge og bronzer",
  "Hudpleie > Serum",
  "Hudpleie > Shampoo",
  "Hudpleie > Tilbehør",
  "Hudpleie > Toner",
  "Hudpleie > Øyenskygge",
  "Hudpleie > Øyeskygge",
  "Hudpleie > Øyne",
  "Hudpleie > Øyne > Serum",
  "Hudpleie > Øyne > Øyekrem",
  "Hudpleie > Øynebryn",
  "Hudpleie >Krem",
  "La Pizza",
  "Sminke",
  "Sminke > Ansikt",
  "Sminke > Ansikt > Concealer",
  "Sminke > Ansikt > Foundation",
  "Sminke > Ansikt > Highlight og Contouring",
  "Sminke > Ansikt > Primer",
  "Sminke > Ansikt > Pudder",
  "Sminke > Ansikt > Rens",
  "Sminke > Ansikt > Rouge og Bronzer",
  "Sminke > Display",
  "Sminke > Display > Krem",
  "Sminke > Display > Lipgloss",
  "Sminke > Display > Øyenbryn",
  "Sminke > Koster",
  "Sminke > Lepper > Leppepomade",
  "Sminke > Lepper > Leppestift",
  "Sminke > Lepper > Lipgloss",
  "Sminke > Lepper > Lipliner",
  "Sminke > Negler",
  "Sminke > Negler > Neglelakk",
  "Sminke > Negler > Neglelakkfjerner",
  "Sminke > Sminkesett",
  "Sminke > Sminkesett > Lipgloss",
  "Sminke > Tilbehør",
  "Sminke > Tilbehør > Krem",
  "Sminke > Øyne",
  "Sminke > Øyne > Eyeliner",
  "Sminke > Øyne > Mascara",
  "Sminke > Øyne > Primer",
  "Sminke > Øyne > Serum",
  "Sminke > Øyne > Øyenbryn",
  "Sminke > Øyne > Øyenskygge",
  "Smittevern",
  "Test",
];
export { categoriestree };

const simplecategories = [
  { id: 21, name: "Hårpleie" },
  { id: 25, name: "Hudpleie" },
  { id: 62, name: "Sminke" },
  { id: 1, name: "Annet" },
];
export { simplecategories };
