export const NewCustomer = [
  {
    id: 1,
    date: "16.12.2023",
    organization_number: "233322134",
    name: "Salongpartner AS",
    contact: "Ola Nordmann",
    email: "ola.nordmann@firmanavn.no",
    phone: "99887766",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
  {
    id: 2,
    date: "16.12.2023",
    organization_number: "142345534",
    name: "Harald og Co AS",
    contact: "Espen Askeladd",
    email: "ola.nordmann@firmanavn.no",
    phone: "11223344",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
  {
    id: 3,
    date: "15.12.2023",
    organization_number: "123412541",
    name: "Kompagni AS",
    contact: "Tore Andre Flo",
    email: "ola.nordmann@firmanavn.no",
    phone: "23423543",
    address: "Omveien 42",
    zip: "3214",
    city: "Kristiansand",
  },
  {
    id: 4,
    date: "14.12.2023",
    organization_number: "123434123",
    name: "Rett Vest Invest AS",
    contact: "Ola Nordmann",
    email: "ola.nordmann@firmanavn.no",
    phone: "23424334",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
  {
    id: 5,
    date: "13.12.2023",
    organization_number: "123123123",
    name: "Rosario Holding AS",
    contact: "Kari Nordmann",
    email: "ola.nordmann@firmanavn.no",
    phone: "12413212",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
];

export const AllCustomer = [
  {
    id: 1,
    date: "16.12.2023",
    organization_number: "233322134",
    name: "Salongpartner AS",
    contact: "Ola Nordmann",
    email: "ola.nordmann@firmanavn.no",
    phone: "99887766",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
  {
    id: 2,
    date: "16.12.2023",
    organization_number: "142345534",
    name: "Harald og Co AS",
    contact: "Espen Askeladd",
    email: "ola.nordmann@firmanavn.no",
    phone: "11223344",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
  {
    id: 3,
    date: "15.12.2023",
    organization_number: "123412541",
    name: "Kompagni AS",
    contact: "Tore Andre Flo",
    email: "ola.nordmann@firmanavn.no",
    phone: "23423543",
    address: "Omveien 42",
    zip: "3214",
    city: "Kristiansand",
  },
  {
    id: 4,
    date: "14.12.2023",
    organization_number: "123434123",
    name: "Rett Vest Invest AS",
    contact: "Ola Nordmann",
    email: "ola.nordmann@firmanavn.no",
    phone: "23424334",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
  {
    id: 5,
    date: "13.12.2023",
    organization_number: "123123123",
    name: "Rosario Holding AS",
    contact: "Kari Nordmann",
    email: "ola.nordmann@firmanavn.no",
    phone: "12413212",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
  {
    id: 6,
    date: "16.12.2023",
    organization_number: "233322134",
    name: "Salongpartner AS",
    contact: "Ola Nordmann",
    email: "ola.nordmann@firmanavn.no",
    phone: "99887766",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
  {
    id: 7,
    date: "16.12.2023",
    organization_number: "142345534",
    name: "Harald og Co AS",
    contact: "Espen Askeladd",
    email: "ola.nordmann@firmanavn.no",
    phone: "11223344",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
  {
    id: 8,
    date: "15.12.2023",
    organization_number: "123412541",
    name: "Kompagni AS",
    contact: "Tore Andre Flo",
    email: "ola.nordmann@firmanavn.no",
    phone: "23423543",
    address: "Omveien 42",
    zip: "3214",
    city: "Kristiansand",
  },
  {
    id: 9,
    date: "14.12.2023",
    organization_number: "123434123",
    name: "Rett Vest Invest AS",
    contact: "Ola Nordmann",
    email: "ola.nordmann@firmanavn.no",
    phone: "23424334",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
  {
    id: 10,
    date: "13.12.2023",
    organization_number: "123123123",
    name: "Rosario Holding AS",
    contact: "Kari Nordmann",
    email: "ola.nordmann@firmanavn.no",
    phone: "12413212",
    address: "Snarveien 42",
    zip: "3214",
    city: "Oslo",
  },
];
export const OrdersData = [
  {
    id: 1,
    customerid: "",
    date: "16.12.2023",
    ordernumber: "652134",
    organization_number: "233322134",
    status: "BEHANDLES",
    contactname: "Ola Nordmann",
    contactemail: "ola.nordmann@firmanavn.no",
    deliveryadress: "Snarveien 42",
    deliveryzip: "3214",
    deliverycity: "Oslo",
    deliverycountry: "Norge",
    orderitems: [],
    totalprice: "399",
  },
  {
    id: 2,
    customerid: "",
    date: "21.07.2023",
    ordernumber: "247135",
    organization_number: "233322134",
    status: "SENDT",
    contactname: "Ola Nordmann",
    contactemail: "ola.nordmann@firmanavn.no",
    deliveryadress: "Snarveien 42",
    deliveryzip: "3214",
    deliverycity: "Oslo",
    deliverycountry: "Norge",
    orderitems: [],
    totalprice: "1199",
  },
  {
    id: 3,
    customerid: "",
    date: "23.04.2023",
    ordernumber: "875323",
    organization_number: "233322134",
    status: "FULLFØRT",
    contactname: "Ola Nordmann",
    contactemail: "ola.nordmann@firmanavn.no",
    deliveryadress: "Snarveien 42",
    deliveryzip: "3214",
    deliverycity: "Oslo",
    deliverycountry: "Norge",
    orderitems: [],
    totalprice: "4229",
  },
  {
    id: 4,
    customerid: "",
    date: "01.04.2023",
    ordernumber: "262436",
    organization_number: "233322134",
    status: "FULLFØRT",
    contactname: "Ola Nordmann",
    contactemail: "ola.nordmann@firmanavn.no",
    deliveryadress: "Snarveien 42",
    deliveryzip: "3214",
    deliverycity: "Oslo",
    deliverycountry: "Norge",
    orderitems: [],
    totalprice: "1423",
  },
  {
    id: 5,
    customerid: "",
    date: "09.03.2023",
    ordernumber: "271634",
    organization_number: "233322134",
    status: "FULLFØRT",
    contactname: "Ola Nordmann",
    contactemail: "ola.nordmann@firmanavn.no",
    deliveryadress: "Snarveien 42",
    deliveryzip: "3214",
    deliverycity: "Oslo",
    deliverycountry: "Norge",
    orderitems: [],
    totalprice: "432",
  },
  {
    id: 6,
    customerid: "",
    date: "28.02.2023",
    ordernumber: "476144",
    organization_number: "233322134",
    status: "FULLFØRT",
    contactname: "Ola Nordmann",
    contactemail: "ola.nordmann@firmanavn.no",
    deliveryadress: "Snarveien 42",
    deliveryzip: "3214",
    deliverycity: "Oslo",
    deliverycountry: "Norge",
    orderitems: [],
    totalprice: "362",
  },
  {
    id: 7,
    customerid: "",
    date: "07.02.2023",
    ordernumber: "234832",
    organization_number: "233322134",
    status: "FULLFØRT",
    contactname: "Ola Nordmann",
    contactemail: "ola.nordmann@firmanavn.no",
    deliveryadress: "Snarveien 42",
    deliveryzip: "3214",
    deliverycity: "Oslo",
    deliverycountry: "Norge",
    orderitems: [],
    totalprice: "4231",
  },
  {
    id: 8,
    customerid: "",
    date: "21.01.2023",
    ordernumber: "243532",
    organization_number: "233322134",
    status: "RETURNERT",
    contactname: "Ola Nordmann",
    contactemail: "ola.nordmann@firmanavn.no",
    deliveryadress: "Snarveien 42",
    deliveryzip: "3214",
    deliverycity: "Oslo",
    deliverycountry: "Norge",
    orderitems: [],
    totalprice: "1634",
  },
  {
    id: 9,
    customerid: "",
    date: "04.01.2023",
    ordernumber: "274153",
    organization_number: "233322134",
    status: "FULLFØRT",
    contactname: "Ola Nordmann",
    contactemail: "ola.nordmann@firmanavn.no",
    deliveryadress: "Snarveien 42",
    deliveryzip: "3214",
    deliverycity: "Oslo",
    deliverycountry: "Norge",
    orderitems: [],
    totalprice: "3124",
  },
  {
    id: 10,
    customerid: "",
    date: "10.12.2022",
    ordernumber: "136342",
    organization_number: "233322134",
    status: "FULLFØRT",
    contactname: "Ola Nordmann",
    contactemail: "ola.nordmann@firmanavn.no",
    deliveryadress: "Snarveien 42",
    deliveryzip: "3214",
    deliverycity: "Oslo",
    deliverycountry: "Norge",
    orderitems: [],
    totalprice: "1354",
  },
];
export const MainAddressData = [
  {
    primary_address: "Kronprinsens gate 41",
    primary_zip: "4614",
    city: "Kristiansand",
  },
];

export const AddressData = [
  {
    id: 1,
    address: "Snarveien 42",
    zip: "3242",
    city: "Lilleby",
  },
  {
    id: 2,
    address: "Snarveien 33",
    zip: "3241",
    city: "Lilleby",
  },
];

export const OrderDetailsData = [
  {
    status: true,
    message: "Order detail has been retrived succesfully.",
    code: 200,
    dateTimeBeforeQryExec: "2019-11-11 08:07:30",
    data: {
      order_data: {
        order_id: "25",
        purchase_order_status_id: 1,
        order_date: "2019-10-21",
        order_number: "100025",
        order_type: "customer_order",
        order_belongs_entity: "customer",
        order_belongs_entity_id: 4526,
        reference: "50",
        comments: null,
        is_locked: true,
        is_locked_at: "2019-10-21 12:54:36",
        is_deleted: false,
        created_at: "2019-10-21 12:54:36",
        updated_at: "2019-10-21 12:54:36",
        is_taken_by_api: true,
        reference_order_number: "50",
        is_paid: null,
      },
      department_data: {
        department_id: 2,
        department_name: "Department name",
        company_number: 888899999,
        department_email: "dept1@gmail.com",
        department_phone: "88889999",
        department_address: "Tors gate 811",
        department_city: "KRISTIANSAND S",
        department_zip: 432,
        department_latitude: "58.12348068580",
        department_longitude: "8.034348919000",
      },
      product_data: [
        {
          entity_type: "product",
          product_id: "316",
          product_name: "Product 1",
          product_number: "2019102110001",
          barcode: "2019102110001",
          cost_price: "0.00",
          stock_price: "0.00",
          vatrate_percent: "25.00",
          price_excluding_vat: "80.00",
          price_including_vat: "100.00",
          discount_percentage: "0.00",
          discount_amount: "0.00",
          quantity: "1.00",
          total_price_excluding_vat: "80.00",
          total_price_including_vat: "100.00",
          total_discount: "0.00",
          original_price_excluding_vat: null,
          original_price_including_vat: null,
          comments: "",
          unit: "g",
          dimension_department_id: 1,
          dimension_department_name: "Dimension name",
          reference_number: 11,
        },
        {
          entity_type: "service",
          product_id: "317",
          product_name: "Service 2",
          product_number: null,
          barcode: null,
          cost_price: null,
          stock_price: null,
          vatrate_percent: "15.00",
          price_excluding_vat: "86.96",
          price_including_vat: "100.00",
          discount_percentage: "0.00",
          discount_amount: "0.00",
          quantity: "1.00",
          total_price_excluding_vat: "86.96",
          total_price_including_vat: "100.00",
          total_discount: "0.00",
          original_price_excluding_vat: null,
          original_price_including_vat: null,
          comments: "",
          unit: null,
        },
      ],
    },
  },
];
export const OrderHistoryData = [
  {
    order_id: "24",
    purchase_order_status_id: 1,
    order_type: "customer_order",
    order_belongs_entity: "customer",
    order_belongs_entity_id: 4526,
    order_number: "100024",
    reference_order_number: "49",
    order_date: "2019-10-21 12:49:34",
    created_at: "2019-10-21 12:51:28",
    updated_at: "2019-10-21 12:51:28",
    reference: "49",
    comments: "",
    is_taken_by_api: true,
    is_locked: "2019-10-21 12:51:28",
    is_deleted: false,
    is_paid: true,
    is_pos: true,
    is_invoice: "",
    employee_id: "2",
    employee_name: "Daniel John",
    customer_id: "4526",
    customer_name: "John max",
    company_number: "",
    customer_phone: "98985688",
    customer_comment: null,
    product_data: [
      {
        entity_type: "product",
        product_id: "101",
        product_name: "Different name",
        price_inc_vat: "100.00",
        quantity: "1.00",
        vatrate_percent: "25.00",
        discount_percentage: "0.00",
        comments: "",
        dimension_department_id: 1,
        reference_number: 11,
      },
      {
        entity_type: "service",
        product_id: "6",
        product_name: "Different name",
        price_inc_vat: "25.00",
        quantity: "1.00",
        vatrate_percent: "25.00",
        discount_percentage: "0.00",
        comments: "",
        reference_number: 11,
      },
    ],
  },
];
